name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-lates

t
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run build
      run: yarn run build